services:
    # Frontend Static Site
    - type: web
      name: frontend
      runtime: static
      rootDir: ./opening-prep # rootDir is correct here for a static build
      buildCommand: "npm install && npm run build"
      staticPublishPath: ./dist
      routes:
          - type: rewrite
            source: /api/(.*)
            destination: https://api.onrender.com/api/$1

    # API Web Service
    - type: web
      name: api
      runtime: docker
      # rootDir has been removed
      dockerfilePath: ./server/Dockerfile.api # Path from repo root
      dockerContext: ./server # Path from repo root
      preDeployCommand: "git lfs install && git lfs pull"
      envVars:
          - key: REDIS_URL
            fromService:
                type: redis
                name: redis-queue
                property: connectionString

    # Worker
    - type: worker
      name: worker
      runtime: docker
      # rootDir has been removed
      dockerfilePath: ./server/Dockerfile.worker # Path from repo root
      dockerContext: ./server # Path from repo root
      preDeployCommand: "git lfs install && git lfs pull"
      envVars:
          - key: REDIS_URL
            fromService:
                type: redis
                name: redis-queue
                property: connectionString

    # Redis Service
    - type: redis
      name: redis-queue
      plan: free
      ipAllowList: []
