services:
    # Frontend Static Site
    - type: web
      name: frontend
      runtime: static
      rootDir: ./opening-prep
      buildCommand: "npm install && npm run build"
      staticPublishPath: ./dist
      routes:
          - type: redirect
            source: /api/(.*)
            destination: https://api.onrender.com/api/$1

    # API Web Service
    - type: web
      name: api
      runtime: docker
      dockerfilePath: ./server/Dockerfile.api
      dockerContext: . # <-- CORRECTED: Use repo root as context
      envVars:
          - key: REDIS_URL
            fromService:
                type: redis
                name: redis-queue
                property: connectionString

    # Worker
    - type: worker
      name: worker
      runtime: docker
      dockerfilePath: ./server/Dockerfile.worker
      dockerContext: . # <-- CORRECTED: Use repo root as context
      envVars:
          - key: REDIS_URL
            fromService:
                type: redis
                name: redis-queue
                property: connectionString

    # Redis Service
    - type: redis
      name: redis-queue
      plan: free
      ipAllowList: []
