services:
    # Frontend Static Site
    # The type is 'web' and the runtime is 'static'.
    # This combination enables the static site features like 'routes'.
    - type: web
      name: frontend
      runtime: static # <-- This was the critical missing key
      rootDir: ./opening-prep
      buildCommand: "npm install && npm run build" # Standard build command property
      publishDir: ./opening-prep/dist # Standard publish directory property
      routes:
          - type: rewrite
            source: /api/(.*)
            destination: https://api.onrender.com/api/$1

    # API Web Service (uses Dockerfile's default CMD)
    - type: web
      name: api
      env: docker
      plan: starter
      rootDir: ./server
      dockerfilePath: ./server/Dockerfile
      dockerContext: ./server
      preDeployCommand: "git lfs install && git lfs pull"
      envVars:
          - key: REDIS_URL
            fromService:
                type: redis
                name: redis-queue
                property: connectionString

    # Worker (overrides Dockerfile's CMD with a startCommand)
    - type: worker
      name: worker
      env: docker
      plan: starter
      rootDir: ./server
      dockerfilePath: ./server/Dockerfile
      dockerContext: ./server
      preDeployCommand: "git lfs install && git lfs pull"
      startCommand: "python worker.py"
      envVars:
          - key: REDIS_URL
            fromService:
                type: redis
                name: redis-queue
                property: connectionString

    # Redis Service
    - type: redis
      name: redis-queue
      plan: free
      ipAllowList: []
