services:
    # 1. The Redis instance for the job queue
    - name: redis
      type: redis
      plan: free

    # 2. The React Frontend
    - name: frontend
      # THE FIX: The correct type is 'static_site'
      type: static_site
      plan: free
      rootDir: ./opening-prep
      buildFilter:
          paths:
              - opening-prep/**
      buildCommand: npm install && npm run build
      publishDir: opening-prep/dist
      envVars:
          - key: VITE_API_URL
            fromService:
                type: web
                name: api
                property: url

    # 3. The FastAPI Web Service
    - name: api
      type: web
      plan: free
      rootDir: ./server
      env: docker
      envVars:
          - key: REDIS_HOST
            fromService:
                type: redis
                name: redis
                property: host
          - key: REDIS_PORT
            fromService:
                type: redis
                name: redis
                property: port

    # 4. The Background Worker
    - name: worker
      type: worker
      plan: free
      rootDir: ./server
      env: docker
      envVars:
          - key: REDIS_HOST
            fromService:
                type: redis
                name: redis
                property: host
          - key: REDIS_PORT
            fromService:
                type: redis
                name: redis
                property: port
