services:
    - type: web
      name: frontend
      env: node
      plan: free
      rootDir: ./opening-prep
      buildCommand: "npm install && npm run build"
      startCommand: "npm run preview"
      envVars:
          - key: VITE_API_URL
            fromService:
                type: web
                name: api
                property: url
      routes:
          - type: rewrite
            source: /api/(.*)
            destination: /api/$1

    - type: web
      name: api
      env: docker
      plan: starter
      rootDir: ./server
      dockerfilePath: ./server/Dockerfile
      dockerContext: ./server
      preDeployCommand: "git lfs install && git lfs pull"
      envVars:
          - key: REDIS_URL
            fromService:
                type: redis
                name: redis-queue
                property: connectionString

    - type: worker
      name: worker
      env: docker
      plan: starter
      rootDir: ./server
      dockerfilePath: ./server/Dockerfile
      dockerContext: ./server
      preDeployCommand: "git lfs install && git lfs pull"
      startCommand: "python worker.py"
      envVars:
          - key: REDIS_URL
            fromService:
                type: redis
                name: redis-queue
                property: connectionString

    - type: redis
      name: redis-queue
      plan: free
