version: "3.8"

services:
    api:
        build: .
        ports:
            - "8000:80"
        environment:
            - REDIS_HOST=redis
        depends_on:
            - redis

    worker:
        build: .
        command: python worker.py
        environment:
            - REDIS_HOST=redis
        depends_on:
            - redis

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
